"""update2

Revision ID: 5b17193a1340
Revises: 8d1d38272885
Create Date: 2024-02-20 05:09:25.893890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b17193a1340'
down_revision: Union[str, None] = '8d1d38272885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'tracking',
        'sold_to_time',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.BigInteger(),  # Используйте BIGINT вместо INTEGER
        existing_nullable=True,
        # Укажите USING для явного преобразования
        postgresql_using="extract(epoch from sold_to_time)::integer"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'tracking',
        'sold_to_time',
        existing_type=sa.BigInteger(),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
        # Укажите USING для явного преобразования
        postgresql_using="to_timestamp(sold_to_time)"
    )
    # ### end Alembic commands ###

