"""init

Revision ID: 8d1d38272885
Revises: 
Create Date: 2024-02-20 04:57:13.190961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d1d38272885'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('sold_to_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('href', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('sold_percentage', sa.Float(), nullable=True),
    sa.Column('total_stock', sa.Integer(), nullable=True),
    sa.Column('sold_stock', sa.Integer(), nullable=True),
    sa.Column('tracking_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tracking_id'], ['tracking.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('href')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection')
    op.drop_table('tracking')
    # ### end Alembic commands ###
