"""update3

Revision ID: b06e6f50e96c
Revises: 5b17193a1340
Create Date: 2024-02-20 05:48:01.078949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b06e6f50e96c'
down_revision: Union[str, None] = '5b17193a1340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection')
    op.drop_table('tracking')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('tracking_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('sold_to_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tracking_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('collection',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('href', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sold_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_stock', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sold_stock', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tracking_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tracking_id'], ['tracking.id'], name='collection_tracking_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collection_pkey'),
    sa.UniqueConstraint('href', name='collection_href_key')
    )
    # ### end Alembic commands ###
